services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environnement:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
