version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environnement:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:lastest
    ports:
      - 80:80
    restart: always
    environnement:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      compose.service.type: LoadBalance